# Generated by Django 5.2.8 on 2025-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruapp', '0002_practica_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
