# Generated by Django 5.2.8 on 2025-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruapp', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('ultima_info', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
